from pathlib import Path

source_path = Path('openscad/p5-64x32-panel/hub75_p5_64x32_panel.scad')
source = source_path.read_text()
old_core = '''    module _rear_frame_core_3d() {\n        difference() {\n            // The outside wall tapers continuously from the rear-housing\n            // start to the mounting plane. The bay cutters remain vertical.\n            _tapered_outer_blank(\n                rear_frame_start_y,\n                mounting_plane_y_value,\n                0,\n                rear_outer_inset_actual\n            );\n\n            _rear_extrude_from_to(\n                rear_frame_start_y - 0.05,\n                mounting_plane_y_value + 0.05\n            )\n                _rear_openings_2d();\n        }\n    }\n'''
new_core = '''    module _rear_frame_core_3d() {\n        difference() {\n            // The full outside wall tapers continuously from the 2.0 mm\n            // rear-housing start to the rear mounting plane. There is no\n            // artificial short chamfer followed by a straight wall.\n            _tapered_outer_blank(\n                rear_frame_start_y,\n                mounting_plane_y_value,\n                0,\n                rear_outer_inset_actual\n            );\n\n            // Keep the bay walls vertical, as in the STEP model.\n            _rear_extrude_from_to(\n                rear_frame_start_y - 0.05,\n                mounting_plane_y_value + 0.05\n            )\n                _rear_openings_2d();\n        }\n    }\n'''
if old_core not in source:
    raise SystemExit('source core block not found')
source_path.write_text(source.replace(old_core, new_core, 1))

doc_path = Path('openscad/p5-64x32-panel/hub75_p5_64x32_panel/design/design.md')
doc = doc_path.read_text()
old_step8 = '''## 8. Combine the three end-relief pieces\n\nThe two triangular transitions and the central rectangle are united into one\nend-relief cutter:\n\n```scad\nmodule _bay_end_relief_2d(z_edge, direction=1) {\n    union() {\n        _bay_end_transition_relief_2d(z_edge, direction, "left");\n        _bay_end_narrow_relief_2d(z_edge, direction);\n        _bay_end_transition_relief_2d(z_edge, direction, "right");\n    }\n}\n```\n\nThe same operation is applied at the bottom and top edge of the bay, with the\ndirection reversed.\n'''
new_step8 = '''## 8. Combine the three end-relief pieces\n\nPhysically the relief still consists of the central rectangle and its two\n45-degree transitions. For the production cutter those three conceptual pieces\nare emitted as **one polygon**. Its base overlaps 0.05 mm into the rounded bay\nopening that is already being removed:\n\n```scad\nmodule _bay_end_relief_2d(z_edge, direction=1) {\n    d = rear_frame_end_step_depth;\n    half_narrow = rear_frame_end_narrow_length/2;\n    cx = width/2;\n    join_overlap = 0.05;\n\n    if(d > 0)\n        polygon([\n            [cx-half_narrow-d, z_edge - direction*join_overlap],\n            [cx-half_narrow,   z_edge + direction*d],\n            [cx+half_narrow,   z_edge + direction*d],\n            [cx+half_narrow+d, z_edge - direction*join_overlap]\n        ]);\n}\n```\n\nThe 0.05 mm overlap lies entirely inside the existing bay opening, so it does\n**not** change the visible STEP-derived relief depth, length or transition\nangles. It only prevents an edge-touch join from surviving extrusion as an\nunwanted vertical wall across the narrow centre section.\n\nThe separate rectangle/triangle helpers shown in steps 5-7 remain useful for\nexplaining and rendering the three physical parts of the profile. The same\ncombined production operation is applied at the bottom and top edge of the bay,\nwith the direction reversed.\n'''
if old_step8 not in doc:
    raise SystemExit('design step 8 block not found')
doc = doc.replace(old_step8, new_step8, 1)

start = doc.index('## 11. Form the 3D rear frame from the cut web')
end = doc.index('\n---\n\n# Reinforcement base geometry', start)
new_step11 = '''## 11. Subtract the four openings from the tapered blank\n\nNow the four complete 2D cutters are extruded through the rear housing and\nsubtracted. The bay walls stay vertical while the outside wall keeps the taper\nfrom the STEP-derived envelope:\n\n```scad\nmodule _rear_frame_core_3d() {\n    difference() {\n        _tapered_outer_blank(\n            rear_frame_start_y,\n            mounting_plane_y_value,\n            0,\n            rear_outer_inset_actual\n        );\n\n        _rear_extrude_from_to(\n            rear_frame_start_y - 0.05,\n            mounting_plane_y_value + 0.05\n        )\n            _rear_openings_2d();\n    }\n}\n```\n\nThe small internal overlap introduced in step 8 is important here: each relief\nis already merged into its rounded bay before extrusion, so the old straight\nbay edge cannot survive as an internal vertical wall through the narrow centre.\n\n**View:** `rear-frame-core`\n\n<!-- scad-render\nview: rear-frame-core\nvpr: [90, 0, 0]\n-->\n\nAt this point the main rear frame exists: two side rails, top/bottom rails and\nthree crossbars.\n\nThis image is also a geometry check. On every crossbar the normal straight bay\nedge must stop at each 45-degree transition; no straight wall or slit may\ncontinue through the central narrow relief. The top and bottom profiles of the\ncrossbar must be corresponding mirror constructions.\n'''
doc = doc[:start] + new_step11 + doc[end:]
doc_path.write_text(doc)
