name: Build HUB75 library

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  build:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-build.yml@v0.6.1
    with:
      artifact_name: lib-scad-hub75-build
