name: PR cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-pr-cleanup.yml@28661fc040c4994e9c1d391285b7425c7a55252b
    with:
      pr_number: ${{ github.event.pull_request.number }}
      pr_branch_prefix: dev/pr
      delete_source_branch: true
