name: SCAD production

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  packages: read

jobs:
  scad:
    uses: brainboxemb/tool.scad-project/.github/workflows/project-production.yml@b86b2be325f64847b8d91b7f2596bfd4e4ffb7f2
    with:
      cache_namespace: lib-scad-hub75-production-v2
