name: Verify

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: read

jobs:
  verify:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    uses: brainboxemb/tool.scad-project/.github/workflows/project-verify.yml@v0.7.2
